language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
  - "pypy"
  - "pypy-5.3.1"
branches:
  only:
    - master
install:
  - pip install coveralls
  - pip install -r requirements.txt
  - pip install -r requirements-dev.txt
  - pip install requests
  - if [[ $TRAVIS_PYTHON_VERSION != 'pypy'* ]]; then pip install ujson; fi
script:
  - python appveyor.py wait
#  - nosetests -v --with-flaky --no-flaky-report --with-coverage --cover-package=telegram/ tests
  - if [[ $TRAVIS_PYTHON_VERSION == 3.5 ]]; then pre-commit run --all-files; fi
  - python appveyor.py build

#  - python ./setup.py bdist_dumb
after_success:
  coveralls
