language: python
python:
  - "2.7"
  - "3.6"

dist: trusty
sudo: false

branches:
  only:
    - master

cache:
  directories:
    - $HOME/.cache/pip
before_cache:
  - rm -f $HOME/.cache/pip/log/debug.log

install:
  - pip install coveralls
  - pip install codecov
  - pip install -U wheel
  - pip install -r requirements.txt
  - pip install -r requirements-dev.txt

script:
  - python travis.py

after_success:
  - coveralls
  - codecov -v -F $TRAVIS_PYTHON_VERSION
