language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
  - "pypy-5.7.1"
  - "pypy3.5-5.8.0"

dist: trusty
sudo: false

branches:
  only:
    - master

cache:
  directories:
    - $HOME/.cache/pip
before_cache:
  - rm -f $HOME/.cache/pip/log/debug.log

install:
  - pip install coveralls
  - pip install -U wheel
  - pip install -r requirements.txt
  - pip install -r requirements-dev.txt
  - if [[ $TRAVIS_PYTHON_VERSION != 'pypy'* ]]; then pip install ujson; fi

script:
  - echo 'Running test suite...' && echo -en 'travis_fold:start:nosetests\\r'
  - nosetests -v --with-flaky --no-flaky-report --with-coverage --cover-package=telegram/ tests
  - echo -en 'travis_fold:end:nosetests\\r'
  - if [[ $TRAVIS_PYTHON_VERSION == 3.5 ]]; then echo 'Running pre-commits...' && echo -en 'travis_fold:start:pre-commmit\\r' && pre-commit run --all-files && echo -en 'travis_fold:end:pre-commit\\r'; fi
  - echo 'Building wheel' && echo -en 'travis_fold:start:bdist_dump\\r'
  - python ./setup.py bdist_dumb
  - echo -en 'travis_fold:end:bdist_dump\\r'

after_success:
  coveralls