name: typing coverage
on:
  pull_request:
    branches:
      - master
      - type_hinting_master
    paths:
      - 'telegram/**'
      - '**.py'
jobs:
  mypy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dependencies and mypy
      run: |
        pip install -r requirements.txt
        pip install -r requirements-dev.txt
        pip install diff-cover lxml
    - name: Verify mypy types
      run: |
        mypy --version
    - name: Running mypy on changed files and save report
      run: |
        python -m mypy -p telegram --cobertura-xml-report . || true
      shell: bash
    - name: Computing typing coverage
      run: |
        diff-cover --fail-under=100 cobertura.xml --html-report typing_coverage.html --compare-branch=origin/$GITHUB_BASE_REF
      shell: bash
    - name: Uploading coverage report as html
      uses: actions/upload-artifact@v1
      with:
        name: typing_coverage
        path: typing_coverage.html