name: Check Type Completeness Monthly Run
on:
  schedule:
    # Run first friday of the month at 03:17 - odd time to spread load on GitHub Actions
    - cron: '17 3 1-7 * 5'
  pull_request:
    # for demo only
    branches:
      - master

jobs:
  test-type-completeness:
    name:   test-type-completeness
    runs-on: ubuntu-latest
    steps:
      - uses: Bibo-Joshi/pyright-type-completeness@1.0.0
        with:
          package-name: telegram
          python-version: 3.12
          pyright-version: ~=1.1.367
      - name: Check Output
        uses: jannekem/run-python-script-action@v1
        with:
          script: |
            completeness = ${{ steps.pyright-type-completeness.outputs.base-completeness-score }}
            if completeness > 1:
                exit(0)
            
            text = f"Type Completeness Decreased to {completeness}. ❌"
            error(text)
            set_summamry(text)
            exit(1)
